name: Use GitHub Secret Safely

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secret safely
        run: echo "The secret is \${{ secrets.SECRET }}"

      - name: Use secret safely
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          echo "Secret is configured for this step"

